name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: 'windows-2019'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1.0.0
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          $ainfo = "Properties\AssemblyInfo.cs"
          $content = (Get-Content -Path $ainfo) -replace '\[assembly: AssemblyVersion\("(?:.+?)"\)\]', ('[assembly: AssemblyVersion("' + "${{ steps.tag.outputs.tag }}".substring(1) + '.*")]')
          $content = $content -replace '\[assembly: AssemblyCopyright\(\"(?:.+?)\"\)\]', ('[assembly: AssemblyCopyright("Copyright © Andy Brandt ' + (Get-Date).year + '")]')
          $content | Set-Content -Path $ainfo
          msbuild /p:Configuration=Release
      - name: Prepare Release
        run: |
          $exe = "keepassnatmsg-proxy.exe"
          $exefull = "bin\Release\"+$exe
          $hash = (Get-FileHash $exefull sha256).Hash.ToLower()
          Set-Content -Path 'release.txt' -Value ('### SHA256 Hash',('* '+$exe),('  * '+$hash))
      - name: Publish Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          body_path: release.txt
          files: |
            bin\Release\keepassnatmsg-proxy.exe