name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: 'windows-2019'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          msbuild